apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    app: {{ include "resource.default.name"  . }}
    giantswarm.io/service-type: "managed"
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: {{ include "resource.default.name"  . }}
        giantswarm.io/service-type: "managed"
    spec:
      template:
        metadata:
          labels:
            app: {{ include "resource.default.name"  . }}
            giantswarm.io/service-type: "managed"
          annotations:
            releaseRevision: {{ .Release.Revision | quote }}
        spec:
          containers:
          - args:
            - --dst-name={{ .Values.destinationRegistry.name }}
            - --dst-user={{ .Values.destinationRegistry.credentials.user }}
            - --last-modified={{ .Values.lastModified }}
            env:
            - name: DST_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: destination-registry-password
                  name: {{ include "resource.default.name"  . }}
            image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            name: {{ include "resource.default.name"  . }}
            volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
          restartPolicy: OnFailure
          serviceAccount: {{ include "resource.default.name"  . }}
          serviceAccountName: {{ include "resource.default.name"  . }}
          volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
