kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "resource.default.namespace"  . }}
  name: {{ include "resource.default.name"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
