{{- if not (((.Values.global).podSecurityStandards).enforced) }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  hostPID: false
  hostIPC: false
  hostNetwork: false
  volumes:
    - secret
    - hostPath
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end }}
