apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  destination-registry-password: {{ .Values.destinationRegistry.credentials.password }}
  source-registry-password: {{ .Values.sourceRegistry.credentials.password }}
  quay-api-token: {{ .Values.sourceRegistry.quayAPIToken }}
