apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    giantswarm.io/service-type: "managed"
type: Opaque
data:
  destination-registry-password: {{ .Values.destinationRegistry.credentials.password }}
