apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.flags.metricsPort }}
      targetPort: {{ .Values.flags.metricsPort }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
