apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metricsPort | quote }}
spec:
  ports:
    - name: prometheus-metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
