apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    app: {{ include "resource.default.name"  . }}
