apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-path: "metrics"
    giantswarm.io/monitoring-port: {{ .Values.flags.metricsPort | quote }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.flags.metricsPort }}
      targetPort: {{ .Values.flags.metricsPort }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
