version: 2.1

orbs:
  architect: giantswarm/architect@4.34.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: crsync
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/crsync"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: "package and push crsync"
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "crsync"
          requires:
            - push-to-quay
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
