apiVersion: v2
name: crsync
description: "Helm chart for crsync retagging tool"
home: "https://github.com/giantswarm/crsync"
version: 0.8.0
appVersion: 0.8.0
annotations:
  application.giantswarm.io/team: honeybadger
