flags:
  includePrivateRepositories: false
  lastModified: 1h
  metricsPort: 8000

destinationRegistry:
  name: docker.io
  credentials:
    user: ""
    # base64 encoded password
    password: ""

sourceRegistry:
  name: quay.io
  credentials:
    user: ""
    # base64 encoded password
    password: ""
  # token with access to read all repos
  quayAPIToken: ""
image:
  name: giantswarm/crsync
  tag: ""
Installation:
  V1:
    Registry:
      Domain: quay.io

podSecurityStandards:
  enforced: false
