flags:
  lastModified: 1h
  includePrivateRepositories: false

destinationRegistry:
  name: docker.io
  credentials:
    user: ""
    # base64 encoded password
    password: ""

sourceRegistry:
  name: quay.io
  credentials:
    user: ""
    # base64 encoded password
    password: ""
  quayAPIToken: "" # token with access to read all repos

image:
  name: giantswarm/crsync
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io

metricsPort: 8000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
