lastModified: 1h

destinationRegistry:
  name: docker.io
  credentials:
    user: ""
    # base64 encoded password
    password: ""

image:
  name: giantswarm/crsync
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
