name: crsync

lastModified: 2h

destinationRegistry:
  name: docker.io
  credentials:
    user:
    # base64 encoded password
    password:

image:
  registry: quay.io
  name: giantswarm/crsync
  tag: "[[ .Version ]]"
